# Generated by Django 5.1 on 2024-09-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="apartment",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.apartment",
            ),
            preserve_default=False,
        ),
    ]
