# Generated by Django 5.1 on 2024-09-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_alter_flat_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensesPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.expense"
                    ),
                ),
            ],
        ),
    ]
