# Generated by Django 5.1 on 2024-09-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_monthlyexpense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="name",
        ),
        migrations.AddField(
            model_name="monthlyexpense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
