# Generated by Django 5.1 on 2024-09-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_monthlyexpense_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="expense",
        ),
        migrations.AddField(
            model_name="monthlyexpense",
            name="expenses",
            field=models.ManyToManyField(to="core.expensesprice"),
        ),
    ]
