# Generated by Django 5.1 on 2024-09-01 22:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_monthlyexpense_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensesprice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expensesprice",
            name="for_date",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
