# Generated by Django 5.1 on 2024-09-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_flat_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="population",
            field=models.IntegerField(default=4),
        ),
    ]
