# Generated by Django 5.1 on 2024-09-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_monthlyexpense_month_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatFeesPerMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_fees", models.IntegerField(default=0)),
                (
                    "flat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.flat"
                    ),
                ),
            ],
        ),
    ]
