# Generated by Django 5.1 on 2024-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_flatfeespermonth_monthly_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="individually",
            field=models.BooleanField(default=False),
        ),
    ]
