# Generated by Django 5.1 on 2024-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_expense_individually"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="total_population",
            field=models.IntegerField(default=0),
        ),
    ]
