# Generated by Django 5.1 on 2024-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_expensesprice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatfeespermonth",
            name="total_fees",
            field=models.FloatField(default=0),
        ),
    ]
