# Generated by Django 5.1 on 2024-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_flatfeespermonth_total_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="sum_of_expenses",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
