# Generated by Django 5.1 on 2024-09-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_monthlyexpense_sum_of_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="flatfeespermonth",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
