# Generated by Django 5.1 on 2024-09-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_monthlyexpense_sum_of_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="expenses",
            field=models.ManyToManyField(
                blank=True, null=True, to="core.expensesprice"
            ),
        ),
    ]
