# Generated by Django 5.1 on 2024-09-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_monthlyexpense_expenses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Money",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="flatfeespermonth",
            name="money",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.money",
            ),
        ),
    ]
