# Generated by Django 5.1 on 2024-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_expensesprice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatfeespermonth",
            name="total_fees",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="money",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlyexpense",
            name="sum_of_expenses",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
